/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apple;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alisha Gupta
 */
public class NewJFramesignup extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramesignup
     */
    public NewJFramesignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("please fill in the following details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(31, 20, 153, 14);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("full name ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 63, 100, 14);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("phone number ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 86, 130, 14);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(38, 112, 80, 14);

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("pin code");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(34, 138, 100, 14);

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(46, 190, 100, 14);

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("city/district/town");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 80, 120, 14);

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("landmark");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(386, 141, 80, 14);

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("alternate phone number");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(360, 170, 170, 14);

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("the above address is ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(9, 307, 170, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 40, 180, 30);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 70, 180, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(160, 110, 180, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(160, 150, 180, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 190, 170, 96);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(503, 80, 140, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(510, 130, 140, 30);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(510, 170, 140, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "my workplace address ", "my residental address", "my other address" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(174, 304, 180, 30);

        jButton1.setText("done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(506, 303, 57, 23);

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("your unique identity code");
        jLabel15.setToolTipText("this is your unique identification code other than your phone number for apple store india to provide you a better service");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(370, 210, 150, 14);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(510, 210, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("hey siri, what next");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(760, 320, 230, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alisha Gupta\\Desktop\\ng\\gsmarena_002 ras2.jpg")); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(630, 280, 700, 370);

        jLabel16.setText("password ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(380, 40, 110, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(500, 30, 140, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alisha Gupta\\Desktop\\ng\\im7.jpg")); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-60, 0, 1570, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
         if (jTextField10.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," fill the detail completely and make sure that none of the detail is left blank");
  if (jTextField1.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," fill the detail completely and make sure that none of the detail is left blank"); 
       if (jTextField2.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," fill the detail completely and make sure that none of the detail is left blank");
           if (jTextField9.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," fill the detail completely and make sure that none of the detail is left blank");
   if (jTextField3.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," fill the detail completely and make sure that none of the detail is left blank");
   if (jTextField4.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," fill the detail completely and make sure that none of the detail is left blank");
  
    if (jTextField6.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," fill the detail completely and make sure that none of the detail is left blank");
    if (jTextField8.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," fill the detail completely and make sure that none of the detail is left blank");
   
    if (jTextArea1.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," fill the detail completely and make sure that none of the detail is left blank");
   
    if (jPasswordField1.getText().isEmpty())
       JOptionPane.showMessageDialog(this ," please make a unique and special password");
    
        
        int a ;
a= Integer.parseInt(JOptionPane.showInputDialog(this,"verify your phone number by the OTP we sent You already, if the OTP did not arraive yet plz wait!"));
if (a==6477) JOptionPane.showMessageDialog(this,"number verified");
if (a==6477)new NewJFramesignin().setVisible(true);
if (a!=6477) JOptionPane.showMessageDialog(this, " number not verified plz try again!!");
  
String c = jTextField10.getText();
String n= jTextField1.getText();
int p1= Integer.parseInt(jTextField2.getText());
int p2= Integer.parseInt(jTextField9.getText());
String e= jTextField3.getText();
int p= Integer.parseInt(jTextField4.getText());
String d= jTextField6.getText();
String l= jTextField8.getText();
String k=jTextArea1.getText();
int t= jComboBox1.getSelectedIndex();
  String pw = jPasswordField1.getText();
  
  
   try{
   
   Class.forName("java.sql.DriverManager");
   Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ip","root","ng77");
   Statement s = (Statement)con.createStatement();
   String q = "insert into customerdetails values('"+c+"','"+n+"','"+p1+"','"+p2+"','"+e+"','"+p+"','"+d+"','"+l+"','"+k+"','"+t+"','"+pw+"');";
   s.executeUpdate(q);
   JOptionPane.showMessageDialog(null,"welcome to apple store india"+" "+ n);
   
   }
    catch(HeadlessException | ClassNotFoundException | SQLException x){
       JOptionPane.showMessageDialog(this,x.getMessage());
  
    }
   
           
   



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped

     
     
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFramesignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFramesignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFramesignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFramesignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFramesignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
