/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apple;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alisha Gupta
 */
public class NewJFramesignin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFramemyaccount
     */
    public NewJFramesignin() {
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("code ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(157, 128, 120, 14);

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("password ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 170, 90, 14);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("sign in");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(294, 27, 130, 14);

        jButton1.setText("continue to shop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 240, 160, 23);

        jButton2.setText("yes, i am new here");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(38, 349, 200, 23);

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("shopping firstime with us ?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(38, 324, 220, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("apple india");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(440, 310, 170, 100);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(290, 170, 140, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 120, 140, 40);

        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alisha Gupta\\Desktop\\ng\\im7.jpg")); // NOI18N
        jLabel5.setText("c");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 700, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new NewJFramesignup().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
        String c = jTextField1.getText();
        String pw = jPasswordField1.getText();
        
        
        try{
         Class.forName("java.sql.DriverManager");
         Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ip","root","ng77");
         Statement s =(Statement)con.createStatement();
         String q="select * from customerdetails where code='"+c+"';";
          ResultSet rs= s.executeQuery(q);
          int n=0;
          
          while(rs.next()){
              String o = rs.getString("code");
              String a = rs.getString("password");
              n++;
              
              if (c.equals(o) && pw.equals(a))
                  new NewJFrameapplle().setVisible(true);
             
               if (c.equals(o) && pw.equals(a))
              JOptionPane.showMessageDialog(this,"now you have signed in");
              
              else 
 JOptionPane.showMessageDialog(this,"either of the code or password did not match! plz try again!!!");
              
              
          }
          rs.close();
          con.close();
          s.close();
          
        
        
        }
        catch( HeadlessException | ClassNotFoundException | SQLException x ){
        JOptionPane.showMessageDialog(this, x.getMessage());
        
        }
        
        
         


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFramesignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFramesignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFramesignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFramesignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFramesignin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
