/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apple;

/**
 *
 * @author Alisha Gupta
 */
public class NewJFrameiphone extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameiphone
     */
    public NewJFrameiphone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "i phone x 64gb", "i phone x 256gb", "i phone 8+ 64gb", "i phone 8+ 256gb", "i phone 8 64gb", "i phone 8 256gb", "i phone 7+ 32 gb", "i phone 7+ 128 gb", "i phone 7+ 256gb", "i phone 7 32 gb", "i phone 7 128gb", "i phone 7 256gb", "i phone 6s+", "i phone 6+", "i phone 6s", "i phone 6" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(288, 134, 215, 40);

        jButton1.setText("show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 223, 80, 40);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("apple");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 14, 110, 30);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("i phone");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(151, 141, 100, 40);

        jButton2.setText("my cart");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(760, 20, 69, 23);

        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(810, 440, 55, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alisha Gupta\\Desktop\\ng\\im12.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, -6, 1090, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       int f;
         f = jComboBox1.getSelectedIndex();
         if (f==0)  new NewJFrameiphonex64().setVisible(true);
         if (f==1)  new NewJFrameiphonex256().setVisible(true);
         if (f==2)  new NewJFrameiphone8plus64().setVisible(true);
         if (f==3)   new NewJFrameiphone8plus256().setVisible(true);
         if (f==4)   new NewJFrameiphone864().setVisible(true);
         if (f==5)    new NewJFrameiphone8256().setVisible(true);
         if (f==6)    new NewJFrameiphone7plus32().setVisible(true);
         if (f==7)    new NewJFrameiphone7plus128().setVisible(true);
         if (f==8)     new NewJFrameiphone7plus256().setVisible(true);
         if (f==9)     new NewJFrameiphone732().setVisible(true);
         if (f==10)     new NewJFrameiphone7128().setVisible(true);
         if (f==11)     new NewJFrameiphone7256().setVisible(true);
         if (f==12)    new NewJFrameiphone6splus().setVisible(true);
         if (f==13)     new NewJFrameiphone6plus().setVisible(true);
         if (f==14)      new NewJFrameiphone6s().setVisible(true);
         if (f==15)     new NewJFrameiphone6().setVisible(true);
             
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 new NewJFramemycart().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new NewJFrameapplle().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameiphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameiphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameiphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameiphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameiphone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
